# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 01:03
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170615_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
